//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.YouTubeSampleData1
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class YouTubeSampleData1 { }
#else

	public class YouTubeSampleData1 : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public YouTubeSampleData1()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/MixTube;component/SampleData/YouTubeSampleData1/YouTubeSampleData1.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private SearchResults _SearchResults = new SearchResults();

		public SearchResults SearchResults
		{
			get
			{
				return this._SearchResults;
			}
		}
	}

	public class SearchResultsItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Title = string.Empty;

		public string Title
		{
			get
			{
				return this._Title;
			}

			set
			{
				if (this._Title != value)
				{
					this._Title = value;
					this.OnPropertyChanged("Title");
				}
			}
		}

		private System.Windows.Media.ImageSource _VideoImageUrl = null;

		public System.Windows.Media.ImageSource VideoImageUrl
		{
			get
			{
				return this._VideoImageUrl;
			}

			set
			{
				if (this._VideoImageUrl != value)
				{
					this._VideoImageUrl = value;
					this.OnPropertyChanged("VideoImageUrl");
				}
			}
		}
	}

	public class SearchResults : System.Collections.ObjectModel.ObservableCollection<SearchResultsItem>
	{ 
	}
#endif
}
